apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: tatchumnono/udagram-api-feed
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "1000Mi"
            limits:
              cpu: 512m
              memory: "2000Mi"
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrete
          volumeMounts:
            - name: aws-secret
              mountPath: /root/.aws/
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
