version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: tatchumnono/*
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  publishLatestToHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker-compose -f docker-compose-build.yaml build --parallel
            docker-compose -f docker-compose-build.yaml push
workflows:
  version: 2
  build-master:
    jobs:
      - publishLatestToHub
