apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  type: ClusterIP
  selector:
    app: frontend
  
